git:
  depth: 1
cache: yarn
language: node_js
matrix:
    fast_finish: true
node_js:
    - 6.0
notifications:
    email:
    - arnab@binary.com
branches:
  only:
  - master
  - dev
before_install: yarn
install: yarn test:full
after_success:
  - yarn test:coveralls
before_deploy:
  - if [ "$TRAVIS_BRANCH" = "master" ] ; then rm -fR www/*; fi
  - if [ "$TRAVIS_BRANCH" = "dev" ] ; then rm -fR www/beta && mkdir www/beta && mv www/* www/beta/; fi
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: './www'
  on:
    branches:
      only:
      - master
      - dev
