git:
  depth: 1
cache: yarn
language: node_js
matrix:
    fast_finish: true
node_js:
    - 6.0
notifications:
    email:
    - arnab@binary.com
branches:
  only:
  - master
  - dev
before_install: yarn
install: yarn test:full
after_success:
  - yarn test:coveralls
  - yarn build
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN
#  local_dir: './www'
#  repo: ''
#  on:
#    branches:
#      only:
#      - master
#      - dev
