language: node_js
node_js:
    - 5.0
notifications:
    email: false
before_install: npm install
install: npm run test:unit
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
