dist: trusty
language: node_js
node_js:
    - 6.0
notifications:
  email:
  - arnab@binary.com
branches:
  only:
  - translations
install:
  - pip install --upgrade pip && pip install -r requirements.txt
  - yarn
  - git checkout translations
  - cd build
  - python3 extract.py
  - cd ..
  - yarn update-translation
after_success:
    - git config --global user.email "arnab@binary.com"
    - git config --global user.name "Arnab Karmakar"
    - git config --global push.default simple
    - git add --all
    - git commit -m 'Commit from TravisCI Build - Translation updated'
    - git remote set-url origin https://$GIT_KEY@github.com/binary-com/binary-next-gen
    - git push origin HEAD:translations
    - mkdir temp-dev-branch
    - cd temp-dev-branch
    - git clone --branch dev https://$GIT_KEY@github.com/binary-com/binary-next-gen --depth 1
    - cd binary-next-gen
    - yarn translate
    - git config --global user.email "arnab@binary.com"
    - git config --global user.name "Arnab Karmakar"
    - git config --global push.default simple
    - git add --all
    - git commit -m 'Commit from TravisCI Build - Translation updated'
    - git push
    - cd ..
    - rm -fR temp-dev-branch
env:
  global:
    secure: TNtKNXrrpzNHvxffdoRKup1JjkRAkN79QhmHJ3s0MiU4QMyGM8Q/3MGhyWlbu1Uk/2BztsQhVy6qonS826QbjCquJkU4Rfs7cXvKnok8OOrQ8To3rSJazip4Bu4hPoW1QC60Jg/wZCzl7Htw6UP69akn5FLRT6REm6ScuzJRHrRfyyse5cztXO/3bokx5vULd+RhcmkUm+/o+4g6g0KtaPA84SC5EQZVGj0Z2Wckw/SsoGv++61sEFnmANFrvzJc6CsriRETSeU8eYxNqMQOPNJijXB22UUWdq+oDFzc52xi+cUpZNt/L+REv0r4XSunUY4OyaxZzciDril7hV4BuIrbuwoTZHaYv3FK2Oc36vbWVbT2Gkp+kUcuKI1QoTkMlXAMmfi39uwCizXVsU7e1fjDczIS+v8eu1gibKW93E2rMbcW/+n/T6d5VHPHPryNDjTW6cDOiZCugwhU5a9ovbcgsdK+3Uq76OXbQWKgaHm6Mj7DCoMwT7jf6BmCbwoaDUostueKrW9vxYNuaCYkiz8rrgBg24q4PO/XC+hExeIo7ZsD2J0PzEwMBqFgFGU19XQblioSLdy5jkMCYLjFX/BsLniHt4Lvm0bUdJw5ORRGRYfc3W2lwL/kf4jayNeP6rbIAKNEvU54ScBnMKHsiRRtVTgZUXDUasn8uM8dN+8=
notifications:
    slack: binary-group:uTqTzdHDhkxPGKKqIB4z70xA
