git:
  depth: 1
cache: yarn
language: node_js
matrix:
  fast_finish: true
node_js:
  - 6.0
notifications:
  email:
  - arnab@binary.com
branches:
  only:
  - master
  - dev
before_install: yarn
install: yarn test:full
after_success:
  - yarn test:coveralls
  - git config --global user.email "arnab@binary.com"
  - git config --global user.name "Arnab Karmakar"
  - git config --global push.default simple
  - if [ "$TRAVIS_BRANCH" = "dev" ] ; then cd build && yarn && yarn deploy:web-beta; fi
  - if [ "$TRAVIS_BRANCH" = "master" ] ; then cd build && yarn && yarn deploy:web-prod; fi
